#!/usr/bin/env bash

#=========================================
# Ubuntu Dev Setup - User Configuration
#=========================================

GIT_NAME="Ronaldo Jiménez"
GIT_EMAIL="rjak727@gmail.com"