#!/usr/bin/env bash

# =========================================
# Ubuntu Dev Setup - User Configuration
# =========================================

GIT_NAME="Ronaldo Jiménez"
GIT_EMAIL="rjak727@gmail.com"

# ==========================================================
# Go
# ==========================================================

GO_VERSION="1.26.6"
GO_ARCH="linux-amd64"

# ==========================================================
# Node.js
# ==========================================================

NODE_VERSION="lts/*"

# ==========================================================
# Flutter
# ==========================================================

FLUTTER_CHANNEL="stable"
FLUTTER_INSTALL_DIR="$HOME/development/flutter"

# ==========================================================
# MongoDB Compass
# ==========================================================

MONGODB_COMPASS_VERSION="1.49.14"

# ==========================================================
# Insomnia
# ==========================================================

INSOMNIA_VERSION="13.1.0"

# ==========================================================
# Antigravity
# ==========================================================

ANTIGRAVITY_IDE_VERSION="2.5.5"
ANTIGRAVITY_IDE_BUILD="4923483625488384"

ANTIGRAVITY_VERSION="2.8.1"
ANTIGRAVITY_BUILD="6512087774658560"
